[general]
import = ["~/.config/alacritty/themes/catppuccin_mocha.toml"]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "SemiBold" }
size = 12
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[window]
decorations = "None"
opacity = 0.9
blur = true

[scrolling]
history = 10000
